version: '3.8'
services:
  server:
    build: ./server
    container_name: cash_bot
    volumes:
      - ./server:/app
    ports:
      - "3010:80"
    env_file: 
      - postgres.env
      - server.env
